# Generated by Django 5.2 on 2025-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('clone', 'Clone Projects'), ('mini', 'Mini Projects'), ('ai', 'AI/ML Projects'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
